data_root: "./user_data/parquet_tardis"
output_root: "./out/user_supplied/data"
tmp_root: "./out/user_supplied/.tmp"
keep_temps: false
exchange: "binance-futures"
symbols: ["SYNTHUSDT"]
dates: ["2025-01-01"]
snapshot_mode: "process"
sod_date: "2025-01-01"
use_quotes: false
num_proc: 1
buffer_size: 200000000
ss_buffer_size: 2000000
base_latency: 0.0
output_format: "npz"
delete_inputs_after: false
